# Generated by Django 3.0.6 on 2020-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TA', 'Text answer'), ('SA', 'Single answer'), ('MC', 'Multiple choice')], max_length=2, verbose_name='Тип'),
        ),
    ]
