# Generated by Django 3.0.6 on 2020-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200510_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TA', 'Ответ с текстом'), ('SA', 'Ответ с выбором одного варианта'), ('MC', 'Ответ с выбором нескольких вариантов')], max_length=2, verbose_name='Тип'),
        ),
    ]
